services:
  - type: web
    name: carbon-tracker
    env: java
    plan: free
    buildCommand: "./mvnw clean package -DskipTests"
    startCommand: "java -jar target/CarbonFootPrintTrackerBackend-0.0.1-SNAPSHOT.jar"
    autoDeploy: true
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: JAVA_VERSION
        value: 17
